### PR TITLE
Update RAK10701-FieldTester.js

### PR DESCRIPTION
**Pull request by myasir926**

### CODE REVIEW

**Comment by beegee-tokyo** [comment]
Will be merged after some tests.

**Comment by beegee-tokyo** [comment]
There is something wrong with the usage of **\`**, **'** and **"**
It throws runtime errors.
The problem is the **\`**:
image

I changed to
```js
		var num_gateways = decoded.num_gw;
		for (idx = 0; idx < num_gateways; idx++) {
			var index = num_gateways - idx - 1;
			decoded["hotspot_${index.toString().padStart(2, '0')}"] = "(${gw_lat[index]},${gw_long[index]})";
		}
```
to get it working.
Can you update your javascript for these changes.

The changed version is working.

**Comment by myasir926** [comment]
Sorry for mistyping. Thanks.

**Comment by beegee-tokyo** [comment]
Still not working. 
Will wait for updates from your side.

**Comment by beegee-tokyo** [comment]
Fixed with another change.

**Pull request closed without merging**
